---
metadata:
  name:  Śląskie Talenty
  short_name: ŚT
  description: Prezentacja aplikacji slaskietalenty.com
  language: en
  pathPrefix: "/"
  siteImage:
  favicon: "/assets/favicon.png"
  themeColor: "#ff0000"
header:
  enabled: true
  logo: "/assets/śt.png"
  logoLink: "/"
  helpUrl: ""
  links:
    - text: Aplikacja
      link: https:slaskietalenty.com
      external: true
    - text: Strona startowa
      link: "/"
      external: false
    - text: Gatsby
      link: https://www.gatsbyjs.org
      external: true

sidebar:
  enabled: true
  # forcedNavOrder:
  #   - "/introduction"
  #   - "/configuration/basic"
  #   - "/configuration/advanced"
  # expanded:
  groups:
    - order: 1
      path: "/gettingstarted"
      title: ":rocket: Jak rozpocząć"
    - order: 2
      path: "/bezpieczenstwo"
      title: ":children_crossing: Bezpieczeństwo"
    - order: 3
      path: "/elementy"
      title: ":computer: Elementy aplikacji"
    - order: 4
      path: "/wniosek"
      title: ":writing_hand: Wniosek"
    - order: 5
      path: "/developing"
      title: ":computer: Developing"
    - order: 6
      path: "/adds"
      title: ":gift: Dodatki"
  links:
    - text: Aplikacja
      link: https://slaskietalenty.com
    - text: React
      link: https://reactjs.org

  ignoreIndex: false
  poweredBy:
    trademark: "/assets/gatsby.png"
    name: GatsbyJS
    link: https://www.gatsbyjs.org
pwa:
  enabled: true
  manifest:
    display: standalone
    crossOrigin: anonymous
    icon: "/assets/favicon.png"

social:
  facebook: https://www.facebook.com/slaskie
  youtube: https://www.youtube.com/user/UMWSla
  twitter: https://twitter.com/prasoweslaskie

features:
  darkMode:
    enabled: true
    default: false
  editOnRepo:
    location: https://github.com/filipowm/boogi
    type: github
    editable: true
  mermaid:
    language: "mermaid"
    theme: "dark"
    options:
    width: 400
    height: 300
  pageProgress:
    enabled: true
    includePaths:
      - "/configuration/settingup/features"
    excludePaths:
      - "/"
    height: 3
    prependToBody: false
    color: "#A05EB5"
  previousNext:
    enabled: true
    arrowKeyNavigation: true
  propagateNetlifyEnv: true
  rss:
    enabled: true
    title: BooGi Docs
    showIcon: false
    copyright: "2020, Mateusz Filipowicz"
    webMaster: "Mateusz Filipowicz"
    managingEditor: "Mateusz Filipowicz"
    categories:
      - Docs as Code
      - GatsbyJS
    ttl: 60
    matchRegex: "^/"
    outputPath: "/rss.xml"
    generator: "boogi"
  scrollTop: true
  search:
    enabled: true
    engine: 'algolia'
    placeholder: 'Przeszukaj'
    startComponent: 'input' # icon
    excerptSize: 8000
    debounceTime: 380
    snippetLength: 23
    hitsPerPage: 10
    showStats: true
    pagination:
      enabled: true
      totalPages: 10
      showPrevious: true
      showNext: true
  showMetadata: true
  toc:
    show: true
    depth: 4
  fullScreenMode: 
    enabled: true
    hideHeader: true
    hideToc: true
    hideSidebar: true
